# Site settings
title: anthonylukach
header-img: img/home-bg.jpg
email: anthonylukach@gmail.com
description: "A place where Anthony Lukach posts about things..."
baseurl: ""
url: "http://alukach.com"
twitter_username: anthonylukach
github_username:  alukach
author: Anthony Lukach
auto: true

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /posts/:title
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
