baseURL: "https://alukach.com/"
languageCode: en-us
title: anthony lukach
copyright: Anthony Lukach
theme: cactus # https://themes.gohugo.io/hugo-theme-cactus/
paginate: 50

googleAnalytics: UA-16401510-1
googleAnalyticsAsync: true

params:
  description: A collection of notes.
  mainSection: posts
  showAllPostsOnHomePage: true
  colortheme: white
  rss: true
  css:
    - css/custom.css
  tagsOverview: false # tag cloud on homepage

  social:
    - name: github
      link: "https://github.com/alukach"
    - name: twitter
      link: "https://twitter.com/anthonylukach"
    - name: linkedin
      link: "https://www.linkedin.com/in/alukach/"
    - name: email
      link: anthony.lukach+blog@gmail.com

  googleDocsResumeId: 1iHOSIBZ7AiSSyyejE1-YS2oOlpxG3JZI_y6llnfxBrI
  googleDocsResumeEmbedId: 2PACX-1vTRJs05NAqIefzyJpU1v0ACAXbkFX1nyOPjMozxsFFqDYYdpFLR-Uq7Gnxy4wnCeLx4pM-AEQNYfNSG

menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: Writings
      url: /posts
      weight: 2
    - name: Resume
      url: /resume
      weight: 2

markup:
  highlight:
    codeFences: true
    guessSyntax: false
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    noClasses: true
    style: rainbow_dash # https://xyproto.github.io/splash/docs/longer/all.html
    tabWidth: 2

  goldmark:
    renderer:
      unsafe: true  # Enable HTML in markdown

minify:
  minifyOutput: true
  tdewolff:
    html:
      keepWhitespace: true  # Persist whitespace to avoid tight clustering of icons on "Find me on..." section of homepage
