baseURL: "https://alukach.com/"
languageCode: en-us
title: anthony lukach
theme: PaperMod # https://adityatelange.github.io/hugo-PaperMod/
paginate: 25

googleAnalytics: UA-16401510-1
googleAnalyticsAsync: true

params:
  homeInfoParams:
    Title: a collection of notes
    Content: thoughts recorded while working as a software developer

  socialIcons:
    - name: github
      url: "https://github.com/alukach"
    - name: twitter
      url: "https://twitter.com/anthonylukach"
    - name: linkedin
      url: "https://www.linkedin.com/in/alukach"

  # Theme config, https://github.com/adityatelange/hugo-PaperMod/wiki/Features
  # (all options default to false)
  ShowReadingTime: true
  ShowToc: true  # default: false
  TocOpen: false  # default: false
  ShowBreadCrumbs: false  # default: false
  ShowCodeCopyButtons: true
  editPost:
    URL: "https://github.com/alukach/alukach.github.io/edit/main/content"
    Text: "Edit" # edit text
    appendFilePath: true # to append file path to Edit link

  googleDocsResumeId: 1iHOSIBZ7AiSSyyejE1-YS2oOlpxG3JZI_y6llnfxBrI
  googleDocsResumeEmbedId: 2PACX-1vTRJs05NAqIefzyJpU1v0ACAXbkFX1nyOPjMozxsFFqDYYdpFLR-Uq7Gnxy4wnCeLx4pM-AEQNYfNSG

  defaultTheme: auto

menu:
  main:
    - name: Posts
      url: /categories/posts
      weight: 2
    - name: Snippets
      url: /categories/snippets
      weight: 3
    - name: Résumé
      url: /resume
      weight: 9
    - name: Search
      url: /Search
      weight: 4

outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search

markup:
  highlight:
    codeFences: true
    guessSyntax: false
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 2

  goldmark:
    renderer:
      unsafe: true # Enable HTML in markdown
